### PR TITLE
Create Service basics

### LINKED ISSUE #188: Add imprint and data security
AFAIK a website need to have an imprint and a data security policy.

Anything else?
What needs to be in there?

### LINKED ISSUE #193: Cookie message and approval
AFAIK before cookies are stored a message needs to be displayed and the user needs to approve that they allow to store cookies.

## My Idea

Have cookie `cookies_allowed`. If this is not set, show some message box at the bottom:
The message something like:

_This sites uses cookies only for session authentication and this message [OK Button]__

When hitting the `[OK Button]`, the `cookies_allowed` cookie is set.

Before storing the session cookie it is checked if the `cookies_allowed` cookie is set, otherwise display somehow that this needs to be agreed on first.

There are some libraries and services out there which does that, I don't think the complexity is very high, so I would do it on my own.

### PR DESCRIPTION
**Pull request by TooAngel**
- Add footer to the frontpage, including `/imprint`, `/privacyPolicy`,
and `public admin`

- Add Imprint
- Add Privacy Policy
- Hash ip addresses in the heroku log, to make sure not to expose
private data

Fixes #188

As far as I understood, if only technical cookies are used, a cookie
message does not need to be shown.
Fixes #193

### CODE REVIEW

**Comment by TooAngel** [comment]
@IanFindlay Would be cool if you can have a look.

- I added an `a` tag to the logo to get back to the front page, which breaks the styling, somehow it gets small and I couldn't figure out quickly what the issue is. Maybe you have a quick idea.
- I changed the styling from the classes (`phases`) to the `h` tags. For a unified design, I think we can use these colors on all `h` tags (e.g. also in the dashboard). If we want to derive we can use classes. WDYT?

**Comment by IanFindlay** [comment]
I think the outer \<a\> tag just needed the class as well or else it was setting the img size based upon the a tag as oppose to the container. I also removed the underline from the logo as that is only for hyperlinks. 

Whilst I was messing about, I removed the slogan which I didn't get chance to do pre-merge, and made the new footer responsive - i.e. on mobile it will be one under the other and on bigger screens it they will all sit adjacent to on another.

My updates to this branch can be found here:
https://github.com/IanFindlay/worlddriven/tree/setup

I don't know if that's the easiest way to help you out, just link my modified branch, so let me know if there is another way you want me to give these changes to you.

**Comment by IanFindlay** [comment]
Also, the update to the \<h\> tags is how I would have done it had I written it. Makes sense to keep the styling consistent throughout the pages as best we can and font colour is perfect for that.

**Comment by TooAngel** [comment]
I included the `class` in the `a` tag and removed the `border-bottom`, so that my improvement does not make it worse.

I have no strong opinion on how to add the other changes. I would let you send a PR for the rest of the changes, especially to distribute the World Driven merge-boost in your direction. I'm also fine to take the rest of your changes, as you prefer.

**Comment by IanFindlay** [comment]
I am probably going to be editing the file again in order to accomplish the clear separation between Phase One and the rest, so if you're happy enough with how it looks for now I can bundle all those changes together. I'm hoping to do that soonish - I'm leaning towards a code folding like dropdown at the moment but I want to give it a little more thought first - but I am more than happy for you to incorporate the changes into this PR if you think they are needed sooner than that.

**Review by IanFindlay — APPROVED** [review]

**Comment by TooAngel** [comment]
> I am probably going to be editing the file again in order to accomplish the clear separation between Phase One and the rest, so if you're happy enough with how it looks for now I can bundle all those changes together. I'm hoping to do that soonish - I'm leaning towards a code folding like dropdown at the moment but I want to give it a little more thought first - but I am more than happy for you to incorporate the changes into this PR if you think they are needed sooner than that.

Sounds good.
I usually suggest making small (whatever that means) iterations, which makes reviewing easier.

Regarding the phases, I think my main idea is:
- Put the auto-merge in the foreground
- Show that there is more than that, something like a vision
- The vision is still blurry

**Comment by IanFindlay** [comment]
I'm fine with the idea of small iterations, it's the way I tend to work, so I may very well wait until this is merged and then make the small changes on their own.

I think the code folding idea is good but perhaps doesn't give the impression you're trying to. Perhaps readable, but noticeably paler, text that can be toggled to normal i.e. dark grey headings and light grey paragraphs that change to the blues and blacks if toggled. Would have to make it clear that it could be toggled so I didn't just look like bad design, but I can see something like that getting across the hazy future plans idea behind it.

**Comment by TooAngel** [comment]
This pull request was merged by [worlddriven](https://www.worlddriven.org).

**Pull request merged**
