### PR TITLE
Update line breaks to paragraph tags (Issue #168)

### LINKED ISSUE #153: Project documentation
I'm still struggling with how to properly explain the idea behind the project.
The last attempt can be found under https://www.worlddriven.org/ or in the `index.html`, reviewing this and improving (not only the english) would be a huge help.

### LINKED ISSUE #168: Update HTML line breaks to paragraph tags
Modern HTML design uses \<p\> tags instead of \<br /> for line breaks. Updating all of the static files in this way should make further styling to the pages easier.

### PR DESCRIPTION
**Pull request by IanFindlay**
Fixes #168 and also updates a few other elements, adds some CSS styling to the first list and corrects a few typos.

Also closes #153 .

### CODE REVIEW

**Comment by IanFindlay** [comment]
@TooAngel I forgot to branch this PR meaning that my fork will be harder to sync when other commits occur. Would you rather I closed this PR and opened a new one from the right branch or should I just leave it as it? Is there an easy way to get the commit history of my master back to being the same as yours without moving these changes to a branch?

**Comment by TooAngel** [comment]
Actually, it doesn't matter (for me) from which branch you are sending the PR. Also, the commit history looks good from my perspective.
To make sure that your commits sit on top of the origin branch you can use `git rebase`. (https://git-scm.com/book/en/v2/Git-Branching-Rebasing)

For this you need to have the `tooangel/worlddriven` repository added as remote.

If you have questions let me know.

**Review by TooAngel — APPROVED** [review]
Looks good, thx.

Also, you could include in the PR description: Fixes #153 - so that the other issue which you addressed in your last PR gets closed, too.

**Comment by IanFindlay** [comment]
> To make sure that your commits sit on top of the origin branch you can use `git rebase`. (https://git-scm.com/book/en/v2/Git-Branching-Rebasing)

Thanks for this link. I'll let this merge then rebase if required.

**Comment by TooAngel** [comment]
This pull request was merged by [worlddriven](https://www.worlddriven.org).

**Pull request merged**
