### PR TITLE
added docker-compose configuration

### LINKED ISSUE #160: Docker / docker-compose setup
To ease up the development environment a container setup would be nice.

The service is using mongodb as a backend, so having a container for that is necessary => docker-compose

For login the service also talks to the github API, best would be if this could be mocked somehow, too (as a bonus)

### PR DESCRIPTION
**Pull request by eriksape**
Fixes #160 
adding the docker-compose configuration

Note: sorry for the new PR I mistaken how to update the branch to the repo

### CODE REVIEW

**Review by TooAngel — APPROVED** [review]
Looks good, thx.

Can you please add `Fixes #160 ` in the Pull Request description so that the issues gets automatically closed?

**Comment by eriksape** [comment]
Ready, thanks @TooAngel

**Comment by TooAngel** [comment]
Due to the merge of the README pull request, this one has a merge conflict. Mind quickly updating it?

**Review by TooAngel — APPROVED** [review]

**Review by IanFindlay — APPROVED** [review]

**Comment by TooAngel** [comment]
This pull request was merged by [worlddriven](https://www.worlddriven.org).

**Pull request merged**
