### PR TITLE
Improve dashboard

### PR DESCRIPTION
**Pull request by TooAngel**
- Introduce css modules for the different components
- Split the dashboard in repositoryList, repository view and pull
request view
- Make repositories clickable, too
- Split up repositoryListItem

The idea of the repository view to give a better overview of that
repository, e.g. some graph showing the contributors and their weigt.
In the Pull Request view we could show only the reviews instead of all
contributors.

### CODE REVIEW

**Comment by TooAngel** [comment]
@IanFindlay - With this PR the dashboard should have the basic functionality I thought of. But it looks shitty :-)
I would highly appreciate it if you could do some design magic. :-)

**Comment by IanFindlay** [comment]
More than happy to take a look. One problem I have with touching anything other than the index.html is previewing the changes. Am I right in thinking that Mongodb needs to be running? If so, any progress on the migration to MariaDB?

**Comment by TooAngel** [comment]
You can use the docker-compose setup, which starts all the necessary containers, including MongoDB.

I'm using: http://localhost:5001/test/dashboard for working on the dashboard, it is filled with mock data, but keeps the dashboard design and logic, so that you don't need to have the GitHub setup and long loading times.

Didn't progress on the MariaDB yet, I wanted to get the dashboard changes out first and was not yet motivated to look into the ORM. It is planned for the next days.

**Comment by TooAngel** [comment]
This pull request was merged by [worlddriven](https://www.worlddriven.org).

**Pull request merged**
