### PR TITLE
Fix for Issue #161

### LINKED ISSUE #161: Change from draft to open
Currently, only the Pull Request open date, the commit date and the latest push (pull request update) date is taken in account.

To trick in a Pull Request you can open a Draft PR, wait the time to merge and change to open and it will be merged directly.

=> For the calculations the date when a PR is changed to open needs to be included.

### PR DESCRIPTION
**Pull request by tomsajuk**
Closes #161 change draft to open.

Getting the events of ready_for_review and checking the last date to update the start date of pull request.
Hope this is okay. If anything else to add please do suggest :) .

### CODE REVIEW

**Review by TooAngel — APPROVED** [review]
Looks good, thx.

I think it would be good, to be a bit more descriptive in the commit/Pull Request description.
`Fix for Issue #161` can be in the content, IMHO in the title and content the solution should be described. Otherwise when reviewing you have to check what #161 actually is.
Anyway, I guess it will be merged anyway like this. :-)

If you like the project and want to continue contributing:
With the different dates, I thought about, instead of filtering the events a couple of times with fixed variables (`ready_for_review`, `unlabel`, `commit`, `pull_request`), it could be also filtered once and only the necessaries are extracted into a dict.
Something like:
```
dates = {};
for event in events:
  if event.event == 'ready_for_review' and dates['ready_for_review'] < event.date:
    dates['ready_for_review'] = event.date
  ...
max_date = max(dates)
```

So have this more dynamic and only show the ones which actually are available.
Understandable? Make sense?

**Comment by tomsajuk** [comment]
@TooAngel I like your suggestion. I will try that out and create a new pull request when done. 
Also shall I add a pull request template?

**Comment by TooAngel** [comment]
> @TooAngel I like your suggestion. I will try that out and create a new pull request when done.
> Also shall I add a pull request template?

Sounds good, both.

**Review by IanFindlay — APPROVED** [review]

**Comment by TooAngel** [comment]
This pull request was merged by [worlddriven](https://www.worlddriven.org).

**Pull request merged**
