### PR TITLE
Improve project documentation (Issue #153)

### PR DESCRIPTION
**Pull request by IanFindlay**
Here is my proofread/edit of the index.html file addressing issue #153 . I hope it is useful to you, feel free to let me know if there are any changes you would like to see.

As a side note @TooAngel , your way of using line breaks instead of \<p\> tags in the html is, I think, a little bit dated. Converting that might be a worthwhile addition, but if you are happy with it as is I won't bother making the issue and/or changing it.

### CODE REVIEW

**Review by TooAngel — APPROVED** [review]
Nice, thx a lot.

Happy if you suggest also line break improvements, I'm pretty sure I'm a bit dated in regards to HTML.

On a side note: I think you understood the world driven idea. Are you aware that as soon your PR gets merged, you have also a certain 'power' to speed up or stop future PRs? :-)

**Comment by IanFindlay** [comment]
> Happy if you suggest also line break improvements, I'm pretty sure I'm a bit dated in regards to HTML.

I think I may very well raise that as an issue and get going on it once this one is merged. It's a small change, but I think modernising the HTML a bit will also help with future additions.
 
> On a side note: I think you understood the world driven idea. Are you aware that as soon your PR gets merged, you have also a certain 'power' to speed up or stop future PRs? :-)

I am, I'm looking forward to seeing how this works in practice as the theory seems rather interesting. You can almost certainly expect my input in the areas I have some knowledge of but much of this is currently unfamiliar to me.

**Comment by TooAngel** [comment]
:-) Sounds good, both

**Comment by TooAngel** [comment]
This pull request was merged by [worlddriven](https://www.worlddriven.org).

**Pull request merged**
